name: BlockBreakCounter
version: ${project.version}
main: me.hsgamer.blockbreakcounter.BlockBreakCounter
softdepend: [LeaderHeads, PlaceholderAPI]
authors: [HSGamer]
description: Count block broken
commands:
  blockbreakcounter:
    description: BlockBreakCounter commands
    usage: /blockbreakcounter
    aliases: [bbc, breakcounter]
permissions:
  blockbreakcounter.help:
    description: Help command
    default: true
  blockbreakcounter.count:
    description: Count command
    default: op
  blockbreakcounter.add:
    description: Add command
    default: op
  blockbreakcounter.set:
    description: Set command
    default: op
  blockbreakcounter.clear:
    description: Clear command
    default: op
  blockbreakcounter.clearall:
    description: Clearall command
    default: op
  blockbreakcounter.reload:
    description: Reload command
    default: op